// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/signup_test/auth_repoImplementation/auth_repoImplementation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:e_commerce_app/core/networking/dio_factory.dart' as _i2;
import 'package:e_commerce_app/features/auth/data/api/auth_api_service.dart'
    as _i4;
import 'package:e_commerce_app/features/auth/data/model/sign_up/signup_request_body.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDioFactory_0 extends _i1.SmartFake implements _i2.DioFactory {
  _FakeDioFactory_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_1<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i4.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DioFactory get dioFactory =>
      (super.noSuchMethod(
            Invocation.getter(#dioFactory),
            returnValue: _FakeDioFactory_0(
              this,
              Invocation.getter(#dioFactory),
            ),
          )
          as _i2.DioFactory);

  @override
  _i5.Future<_i3.Response<dynamic>> signUp({
    required _i6.SignupRequestBody? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {#body: body}),
            returnValue: _i5.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_1<dynamic>(
                this,
                Invocation.method(#signUp, [], {#body: body}),
              ),
            ),
          )
          as _i5.Future<_i3.Response<dynamic>>);
}
