// Mocks generated by Mockito 5.4.6 from annotations
// in e_commerce_app/test/auth_test/cubit/login_cubit/auth_login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:e_commerce_app/config/error/api_result.dart' as _i3;
import 'package:e_commerce_app/features/auth/data/model/login/login_request_body.dart'
    as _i7;
import 'package:e_commerce_app/features/auth/data/model/login/login_response_model.dart'
    as _i6;
import 'package:e_commerce_app/features/auth/domain/repo/auth_repo.dart' as _i2;
import 'package:e_commerce_app/features/auth/domain/use_case/auth_login_use_cases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepo_0 extends _i1.SmartFake implements _i2.AuthRepo {
  _FakeAuthRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthLoginUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLoginUseCases extends _i1.Mock implements _i4.AuthLoginUseCases {
  @override
  _i2.AuthRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeAuthRepo_0(this, Invocation.getter(#authRepo)),
            returnValueForMissingStub: _FakeAuthRepo_0(
              this,
              Invocation.getter(#authRepo),
            ),
          )
          as _i2.AuthRepo);

  @override
  _i5.Future<_i3.ApiResult<_i6.LoginResponseModel>> login({
    required _i7.LoginRequestBody? body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#body: body}),
            returnValue:
                _i5.Future<_i3.ApiResult<_i6.LoginResponseModel>>.value(
                  _FakeApiResult_1<_i6.LoginResponseModel>(
                    this,
                    Invocation.method(#login, [], {#body: body}),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i3.ApiResult<_i6.LoginResponseModel>>.value(
                  _FakeApiResult_1<_i6.LoginResponseModel>(
                    this,
                    Invocation.method(#login, [], {#body: body}),
                  ),
                ),
          )
          as _i5.Future<_i3.ApiResult<_i6.LoginResponseModel>>);
}
